@startuml

' C4 Model diagram
' - https://github.com/plantuml-stdlib/C4-PlantUML
!theme C4_blue_new from <C4/themes>
!include <c4/C4_Container.puml>

' LAYOUT_LANDSCAPE()

Person(personAlias, "Label", "Optional Description")

System_Boundary(c1, "Sample System") {
    Container(containerAlias, "Container Name", "Technology", "Optional Description")
}
Rel(personAlias, containerAlias, "Label", "Optional Technology")

@enduml
