include::header.inc.adoc[]

== Teil 3 - Teamarbeit und Konflikte

In diesem Praktikumsteil geht es um die Zusammenarbeit im Team an einem
gemeinsamen Projekt mit Git und GitHub. Dabei werden typische Konflikte bei der
Zusammenarbeit oder der Verwendung von Branches und deren Lösungsmöglichkeiten
vorgestellt.

:imageFile: grafik_overview_git_teamarbeit.jpg
:imageTitle: Zusammenarbeit im Team mit Git
.{imageTitle}
image::{imageFile}["{imageTitle}", width=800, link="{imagesdir}/{imageFile}"]

include::learning-goals.inc.adoc[tag=03-teamwork]

include::notes-windows-lab.inc.adoc[]

{section-separator}

=== Wie entstehen Konflikte?

Beim Bearbeiten Ihres Projektes kann es an verschiedenen Stellen zu Konflikten
kommen. Dies betrifft unterschiedliche Versionsstände in Branches oder Ihrer
Teammitglieder gegenüber dem entfernten Repository auf GitHub.

Die Konflikte bzw. Unterschiede lassen sich entweder *automatisch*
zusammenführen (_merge_) oder erfordern ein *manuelles* Eingreifen (bspw.
überschneidende Änderungen).

[NOTE]
====
Mit `git merge --abort` lässt sich bei einem Konflikt der aktuelle
Merge-Vorgang abbrechen und in den vorherigen Zustand zurückkehren. So kann der
Konflikt zu einem späteren Zeitpunkt gelöst werden oder weitere Änderungen
vorgenommen werden.
====

:imageFile: grafik_git_push_error.png
:imageTitle: Schritte zum Lösen eines push-Error Konfliktes mit
:imageTitleCmd: git pull
.{imageTitle} `{imageTitleCmd}`
image::{imageFile}["{imageTitle} `{imageTitleCmd}`", width=1024, link="{imagesdir}/{imageFile}"]

:imageFile: grafik_git_push_error2.png
:imageTitle: Schritte zum Lösen eines push-Error Konfliktes
:imageTitleCmd: git pull --rebase
.{imageTitle} `{imageTitleCmd}`
image::{imageFile}["{imageTitle} `{imageTitleCmd}`", width=1024, link="{imagesdir}/{imageFile}"]

.Hinweis: push-Error Konflikte lösen
[%collapsible]
====
=====
Beim Senden *push* (`git push`) der Änderungen des lokalen Repositories zum
Remote-Repository kann es zu einem Konflikt bzw. Fehler kommen, wenn das
Remote-Repository in der Zwischenzeit neuere Versionen (_commits_) erhalten
hat.

In diesem Falle ist es notwendig die aktuelle Version vom Remote-Repository
über ein *pull* (`git pull` oder `git pull --rebase`) zu laden, was zu zwei
Konfliktszenarien führen kann:

Änderung an unterschiedlicher Stelle::
* Variante `git pull`:
.. Git kann Ihre lokalen Änderungen *automatisch* mit der neueren Version vom
   Remote-Repository zusammenführen (*merge*). Es wird automatisch ein neuer
   *Commit* vorbereitet (Message eingeben).
.. Anschließend können Sie mit einem wiederholten *push* die neu
   zusammengeführte Version an das Remote-Repository senden.
* Variante `git pull --rebase`:
.. Git passt die Basis (*rebase*) Ihrer lokalen Änderungen an die neueste Version
   des Remote-Repositories an. Bei einem Konflikt kann mit `git rebase --abort`
   der Vorgang abgebrochen und dieser manuell mit `git pull` gelöst werden.
.. Anschließend können Sie mit einem wiederholten *push* die neu
   zusammengeführte Version an das Remote-Repository senden.

Änderung an gleicher Stelle bzw. Überschneidung::
Git kann Ihre lokalen Änderungen *nicht automatisch* mit der neueren Version vom
Remote-Repository zusammenführen (*mergen*). Die betreffenden Dateien
beinhalten an den sich überschneidenden Zeilen beide Varianten. Oben die lokale
und unten die entfernte Variante. Dies wird wie folgt markiert:
+
--
[source,txt]
----
<<<<<<< HEAD
Änderung 1
=======
Änderung 2
>>>>>>> feb62f7c8cb4201e4f7e2aede0b81c356c1cd31e
----

. Lösen Sie den Konflikt *manuell*, besprechen Sie sich hierzu ggf. im Team,
  durch ein Ersetzen bzw. Vereinen der Änderungen in den betreffenden Dateien.
  Entfernen Sie die durch Git hinzugefügten Markierung.
+
Alternativ entscheiden Sie sich für eine der beiden Versionen: Ersetzen Sie die
Konfliktmarkierungen entweder durch Ihre lokale oder die entfernte Variante:
+
[source,sh]
----
git restore --ours <file_name> <1>
git restore --theirs <file_name> <2>
----
<1> Nimmt Ihre lokale Version +
    ältere Variante: `git checkout --ours <file_name>`
<2> Nimmt die Version vom __remote__-Repository +
    ältere Variante: `git checkout --theirs <file_name>`

. Nehmen Sie die manuell angepasste Änderung (_add_ und _commit_) in Ihr
  lokales Repository auf. Anschließend können Sie mit einem wiederholten *push*
  die neu zusammengeführte Version an das Remote-Repository senden.
--
=====
====

.Hinweis: pull-Error Konflikte lösen
[%collapsible]
====
=====
Sie haben in Ihrem lokalen Repository noch nicht versionierte oder bereits im
INDEX vorgemerkte Änderungen, die auf einem älteren Stand als dem des
Remote-Repositories basieren.

**Variante 1 – Lokale Änderungen versionieren:**

. Nehmen Sie Ihre lokalen Änderungen mit `git add` und `git commit` als neuen
  Commit in Ihr lokales Repository auf.
. Anschließend können Sie mit `git pull` die aktuelle Version des
  Remote-Repositories laden. Git versucht dabei, die lokalen und die
  Remote-Änderungen automatisch zusammenzuführen.
. Falls dabei ein Merge-Konflikt auftritt, muss dieser manuell gelöst werden.
  Siehe hierzu die vorherigen Hinweise zum Thema „Push-Error – Konflikte lösen“.

**Variante 2 – Lokale Änderungen verwerfen:**

Wenn Sie Ihre lokalen Änderungen nicht benötigen, können Sie diese verwerfen.

. Mit `git restore` (neuere Alternative zu `git checkout`) werden Änderungen
  gegenüber dem letzten lokalen Commit bzw. dem INDEX verworfen:
** `git restore :/` – Verwirft alle Änderungen im Repository.
** `git restore .` – Verwirft alle Änderungen im aktuellen Verzeichnis.
** `git restore <file>` – Verwirft die Änderungen in den angegebenen Dateien
   oder Verzeichnissen.
. Anschließend können Sie mit `git pull` die aktuelle Version des
  Remote-Repositories laden.

**Variante 3 – Alle lokalen Änderungen verwerfen:**

. Mit `git reset --hard` werden sowohl die Änderungen im INDEX als auch die
Änderungen im Workspace gegenüber dem letzten lokalen Commit verworfen.
. Anschließend können Sie mit `git pull` die aktuelle Version des
  Remote-Repositories laden.

**Variante 4 – Lokale Änderungen temporär wegspeichern:**

Wenn Sie Ihre lokalen Änderungen zunächst behalten, aber noch nicht
versionieren möchten, können Sie diese mit
https://git-scm.com/docs/git-stash[`git stash`] vorübergehend wegspeichern.

. `git stash` speichert die lokalen Änderungen und setzt den Workspace auf den
  Stand des letzten lokalen Commits zurück.
. Anschließend können Sie mit `git pull` die aktuelle Version des
  Remote-Repositories laden.
. Mit `git stash pop` können Sie die zuvor gespeicherten Änderungen wieder in
  den Workspace übernehmen.
. Falls dabei ein Konflikt auftritt, muss dieser manuell gelöst werden.
  Siehe hierzu die vorherigen Hinweise zum Thema „Push-Error – Konflikte lösen“.
=====
====

.Hinweis: Fehler bei fehlendem Standardverhalten bei `git config pull`
[%collapsible]
====
=====
Ist kein Standardverhalten für den Umgang mit neuen Versionen und lokalen
Versionen bei einem `pull` angegeben, muss dies noch zusätzlich in die
*.gitconfig* mit aufgenommen werden.

.Fehlermeldung:
[source,txt]
----
Hinweis: Sie haben abweichende Branches und müssen angeben, wie mit diesen
Hinweis: umgegangen werden soll.
Hinweis: Sie können dies tun, indem Sie einen der folgenden Befehle vor dem
Hinweis: nächsten Pull ausführen:
Hinweis:
Hinweis:   git config pull.rebase false  # Merge <1>
Hinweis:   git config pull.rebase true   # Rebase <2>
Hinweis:   git config pull.ff only       # ausschließlich Vorspulen <3>
Hinweis:
Hinweis: Sie können statt "git config" auch "git config --global" nutzen, um
Hinweis: einen Standard für alle Repositories festzulegen. Sie können auch die
Hinweis: Option --rebase, --no-rebase oder --ff-only auf der Kommandozeile nutzen,
Hinweis: um das konfigurierte Standardverhalten pro Aufruf zu überschreiben.
Schwerwiegend: Es muss angegeben werden, wie mit abweichenden Branches umgegangen werden sollen.
----
<1> Es wird eine neue Version erzeugt, welche das vereinte Ergebnis der
    lokalen und gepullten Versionen enthält.
<2> Es wird die Basis der lokalen Versionen auf die neu gepullte Versionen
    aktualisiert.
<3> Es wird keine neue Version erzeugt, sondern nur die neuen Versionen
    geladen. Es tritt ein Fehler auf, wenn es lokale Versionen gibt und es muss
    händisch ein Merge oder Rebase durchgeführt werden.
=====
====


{section-separator}

// The original comic is from the Geek&Poke comic series.
// Geek&Poke - The New Developer
// https://geek-and-poke.com/geekandpoke/2012/4/25/the-new-developer.html
:imageTitle: The New Developer
:imageFile: comic_the-new-developer.jpg
.{imageTitle} footnote:[Von den Geek&Poke Comics inspiriert. (https://geek-and-poke.com/geekandpoke/2012/4/25/the-new-developer.html[Original])]
image::{imageFile}["{imageTitle}", width=250, role="right"]

=== 1. Einrichtung des Teams

Für die Bearbeitung der Aufgaben bilden Sie bitte Teams aus zwei Personen.
Entscheiden Sie selbst, wer der Verantwortliche für das Git-Repository ist.

.Rollen im Team:
- icon:user[] **Person A** ... Mitglied im Team, Repository-Eigentümer
- icon:user[] **Person B** ... Mitglied im Team

Sind Sie zu dritt, gibt es eine Rolle icon:user[] **Person C** mit ähnlichen
Aufgaben wie Person B. Nehmen Sie hier beispielsweise die Erfassung der
verwendeten Software in einer Datei _Software.adoc_.


==== Aufgabe 1.1 - Repository erstellen

.icon:user[] Person A
Erstellen Sie in Ihrem GitHub-Account ein neues *_privates_* Repository
*htwd-se-example-teamproject* mit folgenden Einstellungen:

* Repository name: `htwd-se-example-teamproject`
* Description: `Beispielteamprojekt für die Praktikumsaufgaben zum Thema Git und AsciiDoc`
* Initialize this repository with a README: `Ja`

==== Aufgabe 1.2 - Mitglieder hinzufügen

.icon:user[] Person A
Fügen Sie Ihrem Repository *htwd-se-example-teamproject* über die Einstellungen
"Settings > Collaborators > Manage access > Add people" Ihre
Teammitglieder über den Account-Namen oder die E-Mail hinzu.

:url-01: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/repository-access-and-collaboration/permission-levels-for-a-personal-account-repository
:url-01-text: Permission levels for a personal account repository

NOTE: Alle Mitglieder haben Schreibrechte und können gleichberechtigt
Änderungen am Repository vornehmen. Siehe auch {url-01}[{url-01-text}].

.icon:user[] Person B
Schauen Sie in Ihr Mail-Postfach und nehmen Sie die Einladung zum
*htwd-se-example-teamproject* an. Öffnen Sie anschließend das Team-Repository
auf GitHub von Person A.

NOTE: Damit der Einladungslink funktioniert, müssen Sie im Webbrowser schon
bei GitHub angemeldet sein.

==== Aufgabe 1.3 - Repository Clonen

.icon:users[] Person A, B
Clonen Sie jeweils das Repository *htwd-se-example-teamproject* von Person A in
Ihr Studentenlaufwerk, bspw. unter `U:\praktika\se\`, oder an geeigneter Stelle
lokal auf Ihren Rechner.


{section-separator}

=== 2. Bearbeiten des Projektes

==== Aufgabe 2.1 - vorgegebene Reihenfolge

Es tritt kein Konflikt auf, da die Teammitglieder in einer vorgegebenen
Reihenfolge arbeiten und sich nicht gegenseitig überschreiben. Diese Variante
ist in der Praxis eher untypisch, da hier jeder immer auf den Stand des anderen
warten muss, bevor er mit der Bearbeitung beginnen kann.

.icon:user[] Person A
1. Erstellen Sie im lokalen Workspaces Ihres *htwd-se-example-teamproject*
   Repositories ein Verzeichnis *docs* und legen Sie in diesem eine neue Datei
   *_Teamdokumentation.adoc_* mit folgendem Inhalt in Visual Studio Code an:
+
.Teamdokumentation.adoc
[source,asciidoc]
----
= Teamdokumentation
Vorname Nachname <email>
0.1, 01.09.2019
:toc:
:toc-title: Inhaltsverzeichnis
// Platzhalter für weitere Dokumenten-Attribute

== Einführung
Dieses Dokument dient im Praktikum als Spielwiese für das Kennenlernen und
praktische Üben von AsciiDoc und Teamarbeit mit Git.
----
2. Speichern Sie und nehmen Sie Ihre Änderungen als neue Version in Ihr lokales
   Git-Repository und Ihr Team-Repository auf GitHub auf.

.icon:user[] Person B
1. Aktualisieren Sie mit "... > Pull" Ihr lokales Repository mit dem Stand vom
   entfernten Repository auf GitHub.
2. Legen Sie in Ihrem Repository die neue Datei *Teammitglieder.adoc* im
   Verzeichnis *docs* mit folgendem Inhalt in Visual Studio Code an:
+
.Teammitglieder.adoc
[source,asciidoc]
----
== Teammitglieder
----
3. Speichern Sie und nehmen Sie Ihre Änderungen als neue Version in Ihr lokales
   Git-Repository und das Team-Repository auf GitHub auf.

.icon:users[] Person A, B
Aktualisieren Sie Ihr lokales Repository (`git pull`), damit *jeder* den
gleichen Stand wie das gemeinsame Team-Repository auf GitHub hat.

.Aktuelle Projektstruktur:
[source,txt]
----
htwd-se-example-teamproject
├── docs
│   ├── Teamdokumentation.adoc
│   └── Teammitglieder.adoc
└── README.md
----

==== Aufgabe 2.2 - freie Teamarbeit

Bearbeiten Sie im Team die folgenden Aufgaben und nehmen Sie jeweils *jede
einzelne gelöste Aufgabe* als neue Version in Ihr lokales (`git commit`) und
Ihr entferntes (GitHub) Teamrepository (`git pull`) auf.

Es ist keine bestimmte Reihenfolge vorgegeben, nur was wer tun soll. Versuchen
Sie aufgetretene __merge__-Konflikte zu lösen oder provozieren Sie diese.

NOTE: Beim Hinzufügen Ihres Namens, beachten Sie die Hinweise unter
<<01-basics.adoc#id-multiple-authors, Verwendung von mehreren Autoren>>.

.Aufgaben - icon:user[] Person A
- Ergänzen Sie in der Datei *_Teamdokumentation.adoc_* im Dokumentenkopf Ihren
  Namen und Ihre E-Mail.
- Binden Sie in der Datei *_Teamdokumentation.adoc_* an geeigneter Stelle die
  Datei _Teammitglieder.adoc_ (wenn vorhanden auch die _Software.adoc_) über
  https://docs.asciidoctor.org/asciidoc/latest/directives/include/[includes] ein.
- Passen Sie in der Datei *_README.md_* den Titel an und fügen Sie eine kurze
  Beschreibung hinzu.

.Aufgaben - icon:user[] Person B
- Ergänzen Sie in der Datei *_Teamdokumentation.adoc_* im Dokumentenkopf Ihren
  Namen und Ihre E-Mail.
- Legen Sie in der Datei *_Teammitglieder.adoc_* eine
  https://docs.asciidoctor.org/asciidoc/latest/tables/build-a-basic-table/[Tabelle]
  mit den Namen und der Rolle der Teammitglieder an.
- Legen Sie eine Datei .gitignore an, um HTML- und PDF-Dateien im Verzeichnis
  `docs/` vom Repository auszuschließen.

.Endaufgabe - icon:users[] Person A, B
. Aktualisieren Sie, wenn alle Aufgaben erledigt sind, Ihr lokales Repository.
. Lassen Sie sich in VS Code über die AsciiDoc-Erweiterung die Vorschau der
  fertigen Datei *_Teamdokumentation.adoc_* anzeigen und den Projektverlauf
  (commit history) in Ihrem GitHub-Repository.


include::sitemap.inc.adoc[]
