include::header.inc.adoc[]

== Teil 4 - Aufgabenmanagement

include::learning-goals.inc.adoc[tag="04-issues-projects"]

include::notes-windows-lab.inc.adoc[]

{section-separator}


=== 1. GitHub Issues

GitHub bietet mit dem Bereich *Issues* eine Möglichkeit anstehende Aufgaben,
aufgetretene Probleme und mögliche Verbesserungen zentral in Ihrem Projekt
innerhalb Ihres Repository zu verwalten und zu diskutieren.

- https://docs.github.com/en/issues[GitHub Issues]
- https://docs.github.com/en/issues/tracking-your-work-with-issues/learning-about-issues/quickstart[Quickstart for GitHub Issues]

:image-title: Screenshot: Bereich Issues auf GitHub
:image-file: screenshot_github_issues.png
.{image-title}
image::{image-file}["{image-title}", width=800, link="{imagesdir}/{image-file}"]

Jeder Issue (Aufgabe, Ticket, ...) besteht aus einem *Titel* und der
*Beschreibung* des Sachverhaltes. Zusätzlich können zur besseren Verwaltung
noch *Assignees* (Beauftrage), *Labels* und weitere Kriterien hinzugefügt
werden. Ebenfalls kann über *Kommentar* der Issue diskutiert und mit
Anmerkungen versehen werden. Eine detaillierte Beschreibung finden Sie in dem
Guide: https://guides.github.com/features/issues/[Mastering Issues]

Bei Verwendung bestimmter *Keywords*
(https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword[Closing
issues using keywords]) in den Commit Messages können *referenzierte Issues*
automatisch geschlossen werden.

.Hinweise: Verwenden von Referenzen in Issue-Kommentaren und Commits
[%collapsible]
====
=====
In den Issues und Commits können in den Kommentaren/Mitteilungen Verweise auf
andere Elemente verwendet werden. Diese werden von GitHub automatisch verlinkt.

[#table_verweise]
.Ausgewählte Verweise
[cols="1,1,3"]
|===
| *Issue*  | Nummer      | `#2`
| *Commit* | SHA hash    | `5000fb638483c95d5f0346181af32096db2d23ff`
| *User*   | Accountname | `@account`
|===

Siehe auch: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls[Autolinked references and URLs]

Beispiele:

* Commit Message:
** `Setze Erweiterung aus Issue #2 um`
** `Setze Erweiterung um (#2)`
* Commit Message mit automatischem Schließen der zugehörigen Issue:
** `Korrigiere Fehler (close #2)`
* Issue Kommentar:
** `... siehe Commit 479bcfca71f10423c0f1181853017b83af062c46`
=====
====

==== Vorbereitung

. Verwenden Sie für die Bearbeitung der Aufgaben Ihr Team-Repository
  *htwd-se-example-teamproject* mit der gleichen Teamzusammenstellung
  aus dem letzten Praktikum.
+
Falls Sie in einer neue Teamzusammenstellung sind, legen Sie ein neues
Repository an und fügen Sie die entsprechenden Teammitglieder als
Collaborators hinzu.

. Öffnen Sie Ihr Team-Repository auf GitHub und in VS Code auf Ihrem Rechner.


==== Aufgabe 1.1 - Issues

. Jeder erstellt *ein* Issue mit einem Titel und einer Beschreibung, die eine
  kleine beispielhafte Aufgabe, ein Problem oder eine Verbesserung darstellt.
. Weisen Sie der Issue ein Label zu (z.B. `task`, `bug`, `enhancement`) zu.
. Diskutieren Sie die Issue im Kommentarbereich, um weitere Details zu klären
  oder Feedback zu geben.

==== Aufgabe 1.2 - Sub-Issues

. Legen Sie für Ihr eben erstelltes Issue zwei Sub-Issues an, um sie in
  konkretere Aufgaben zu unterteilen.
. Weisen Sie *einer* Sub-Issue ein Teammitglied zu (Assignee).

==== Aufgabe 1.3 - Issues bearbeiten

. Bearbeiten Sie in VS Code die *eine* Ihnen zugewiesene Issue.
. Nehmen Sie das Ergebnis als neue Version, mit einer Referenz zur Issue, in
  Ihr lokales Repository auf und synchronisieren Sie es mit GitHub.
. Schließen Sie die Issue manuell auf GitHub oder automatisch über eine erneute
  Version mit entsprechender Commit Message.

{section-separator}

=== 2. GitHub Projects

[NOTE]
====
A project is an adaptable collection of items that you can view as a table,
a kanban board, or a roadmap and that stays up-to-date with GitHub data. Your
projects can track issues, pull requests, and ideas that you note down.
- https://docs.github.com/de/issues/planning-and-tracking-with-projects[GitHub
Projects]
====

// TODO: Beispiel Screenshot eines GitHub Projects einfügen

.Was sind GitHub Projects?
Mit Hilfe von GitHub Projects können Aufgaben (Issues und Pull Requests) eines
oder mehrerer Projekte in separaten Sichten organisiert werden. Sie bieten eine
flexible Möglichkeit, Aufgaben zu planen, zu priorisieren und den Fortschritt
im Blick zu behalten.

.Was sind Sichten und Boards?
Ein GitHub Project enthält anpassbare Sichten (Views), um die Aufgaben in einem
Projekt zu organisieren, zu verfolgen und zu verwalten. Es gibt verschiedene
Arten von Sichten, wie z.B. Tabellen, Boards oder Roadmaps, die jeweils
unterschiedliche Möglichkeiten bieten.

Weitere Informationen in der offiziellen Dokumentation von GitHub:

- https://docs.github.com/de/issues/planning-and-tracking-with-projects[GitHub
Projects]
** https://docs.github.com/en/issues/planning-and-tracking-with-projects/creating-projects[Creating projects]
** https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-items-in-your-projects[Managing items in your projects]
** https://docs.github.com/en/issues/planning-and-tracking-with-projects/understanding-fields[Understanding fields]
** https://docs.github.com/en/issues/planning-and-tracking-with-projects/customizing-views-in-your-project/filtering-projects[Filtering projects]


==== Vorbereitung

Für die Folgenden Aufgaben benötigen wir wieder Ihr eigenes *htwd-se-example-project*
Repository aus den ersten Praktika.

. Öffnen Sie auf GitHub Ihr *htwd-se-example-project* Repository.
. Legen Sie eine neue Issue an:
** Issue: `GitHub Project einrichten`, Label: `project-task`

==== Aufgabe 2.1 - Projekt anlegen

. Legen Sie ein neues GitHub Project im Reiter *Projects* mit dem Button btn:[+
  New project] in Ihrem *htwd-se-example-project* Repository an:
** Template: `Table` (Start from scratch)
** Name: `Example Project`
** Import `Open issues` from repository: `htwd-se-example-project`

==== Aufgabe 2.2 - Felder anlegen

. Passen Sie über "Field settings..." die Werte der Spalte *Status* an:
** umbenennen von `Todo` in `New`
** anlegen von `Ready`, `In Progress`, `In Review`, `Done` (sofern nicht schon
   vorhanden)
** Passen Sie ggf. die Reihenfolge und die Farben an.

. Legen Sie ein neues Feld *Priority* über btn:[+ New field] an:
.. Feldeigenschaften:
*** Field name: `Priority`
*** Field type: `Single select`
*** Options: `P0` (Kritisch), `P1` (Hoch), `P2` (Mittel), `P3` (Niedrig)
.. Fügen Sie jeweils eine passende Beschreibung sowie Farbe hinzu und passen Sie
  ggf. die Reihenfolge an:
*** P0: `Kritisch (Must have)` (bspw. rot)
*** P1: `Hoch (Should have)` (bspw. orange)
*** P2: `Mittel (Could have)` (bspw. gelb)
*** P3: `Niedrig (Nice to have)` (bspw. grau)

. Legen Sie ein neues Feld *Sprint* an:
+
--
** Field name: `Sprint`
** Field type: `Iteration`
** Starts on: Montag der aktuellen Woche
** Duration: `2 weeks`

Damit werden automatisch drei Sprints (`Sprint 1`, `Sprint 2` und `Sprint 3`),
ausgehen vom Startdatum und mit der Zeitraumdauer, angelegt.
--

. Legen Sie ein neues Feld *Estimate* an:
** Field name: `Estimate`
** Field type: `Number`

==== Aufgabe 2.3 - Product Backlog

Anzeige aller offenen Aufgaben, insbesondere User Stories, Bugs, Spikes und
technische Stories.

:image-title: Screenshot: GitHub Project - Product Backlog
:image-file: screenshot_github_project_product_backlog.png
.{image-title}
image::{image-file}["{image-title}", width=800, link="{imagesdir}/{image-file}"]

Dies dient als Grundlage, um zu klären, welche Aufgaben `neu` oder `ready` für
die Bearbeitung sind.

. Benennen Sie die vorhandene *View* (Sicht) in `Product Backlog` um.

. Passen Sie den Filter wie folgt an:
** Filter: `is:open label:user-story,technical-story,spike,bug no:sprint`

. Blenden Sie die Anzeige folgender Spalten aus (Hide field):
** `Assignees`, `Labels`, `Linked pull requests`, `Sprint`, `Sub-issues progress`

. Legen Sie zwei neue Issues mit dem Label `user-story` an:
** Issue: `Benutzer kann sich anmelden`, Label: `user-story`
** Issue: `Benutzer kann seinen Account verwalten`, Label: `user-story`

. Ändern Sie den Status der angelegten User-Story `Benutzer kann sich anmelden` auf `Ready`.

==== Aufgabe 2.4 - Sprint Planning

Anzeige aller offenen Aufgaben gruppiert nach Ihrer Zuordnung zu den Sprints.

:image-title: Screenshot: GitHub Project - Sprint Planning
:image-file: screenshot_github_project_sprint_planning.png
.{image-title}
image::{image-file}["{image-title}", width=800, link="{imagesdir}/{image-file}"]

Dies dient als Grundlage für die Planung der nächsten Iteration/Sprint, um die
Übersicht über alle offenen (Ready) Aufgaben zu behalten.

. Legen Sie eine neue Sicht als *Tabelle* mit dem Namen *Sprint Planning* an.

. Passen Sie den Filter wie folgt an:
** Filter: `is:open label:user-story,technical-story,spike,bug,task,project-task`
// +
// optional zusätzlich: `-status:New`

. Passen Sie die zu verwendenden Spalten an:
** Titel, Status, Priority, Sprint, Estimate

. Gruppieren Sie die Tabelle nach dem Feld *Sprint* (Settings View):
** Group by: `Sprint`

. Weisen Sie die folgenden Aufgaben (Issues) dem Sprint `Sprint 1` zu:
** `GitHub Project einrichten`
** `Benutzer kann sich anmelden`

. Legen Sie zur User-Story `Benutzer kann sich anmelden` zwei neue Sub-Issues an:
*** Sub-Issue: `API-Endpunkt für Login erstellen`, Label: `task`, Sprint: `Sprint 1`
*** Sub-Issue: `Registrierungsformular implementieren`, Label: `task`, Sprint: `Sprint 1`


==== Aufgabe 2.5 - Current Sprint

Anzeige aller Aufgaben, die aktuell in Bearbeitung sind, gruppiert nach ihrem
Status.

:image-title: Screenshot: GitHub Project - Current Sprint
:image-file: screenshot_github_project_current_sprint.png
.{image-title}
image::{image-file}["{image-title}", width=800, link="{imagesdir}/{image-file}"]

Dies dient als Übersicht über den Fortschritt der Aufgaben im aktuellen
Sprint.

. Legen Sie eine neue Sicht als *Board* mit dem Namen *Current Sprint* an.
+
Standardmäßig wird *Status* als Basis für die Spalten des Boards verwendet.

. Passen Sie den Filter wie folgt an:
** Filter: `sprint:@current label:task,project-task -status:Ready`

. Bewegen Sie die Issue `GitHub Project einrichten` in die Spalte `In Progress`.

{section-separator}

=== Extras

==== Issue Check-Lists

In den Issue-Beschreibungen können auch Aufgabenlisten angelegt werden. Dies
können Teilschritte einer Issue sein oder eine Art Check-Liste, ob bspw. alle
genannten Teammitglieder diese erfüllt haben. Bei Bedarf können Teilaufgaben
auch in Sub-Issues oder neue Issues umgewandelt werden.

Siehe auch: https://docs.github.com/de/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists[Informationen zu Aufgabenlisten]

.Hinweise: Beispiele für Aufgabenlisten in Issues
[%collapsible]
====
=====
.Beispiel für Teilaufgaben:
[source, markdown]
----
Abnahmekriterien:

- [ ] Teilaufgabe 1 erledigt
- [ ] Feedback eingeholt
- [ ] Dokumentation aktualisiert
- [ ] ...
----

.Beispiel für eine Check-Liste:
[source, markdown]
----
Macht euch mit Aufgabenlisten vertraut.

- [ ] Person A
- [ ] Person B
----
=====
====

{section-separator}

==== Issue Templates

Mit Hilfe von
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates[Issue-Templates]
können Vorgaben (wie Labels) und Strukturen für verschiedene Issues-Arten (User
Stories, Tasks, Risiken, usw.) definiert werden.
Diese Vorlage kann dann beim Erstellen einer Issue ausgewählt werden.

- Repository-Einstellungen -> General -> Features -> Issues -> kbd:[Set up templates]
- Die Templates werden unter dem Verzeichnis `.github/ISSUE_TEMPLATE/` im
  Repository gespeichert und mit versioniert.

{section-separator}

==== Issues Filters

In der *Issues* Anzeige von GitHub werden alle vorhandenen *Issues* und *Pull
Requests* aufgelistet. Standardmäßig ist die Sicht mit `is:issue is:open` auf
offene Issues gefiltert.

:image-title: Issue-Ansicht in GitHub
:image-file: screenshot_github_issues_filter.jpg
.{image-title}
image::{image-file}["{image-title}", width=800, link="{imagesdir}/{image-file}"]

.Hinweise zu den Filtermöglichkeiten
[%collapsible]
====
=====
Für eine gezielte Sicht auf bestimmt Einträge, gibt es eine Vielzahl an
Filtermöglichkeiten und deren Kombination. Ausgewählte finden Sie in der
<<table_filterkriterien>> und eine komplette Liste und weitere Informationen
unter folgenden Links:

- https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests[Searching issues and pull requests]
- https://docs.github.com/en/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax[Understanding the search syntax]
- https://docs.github.com/en/search-github/getting-started-with-searching-on-github/sorting-search-results[Sorting search results]

.Ausgewählte Filterkriterien
[#table_filterkriterien]
[cols="1,3"]
|===
| Filter      | Beschreibung

| `is:pr`     | Pull-Requests
| `is:issue`  | Issues
| `is:open`   | offen
| `is:closed` | geschlossen
| `author:USERNAME` | von einem Nutzer erstellt
| `assignee:USERNAME` | einem Nutzer zugewiesen
| `label:LABEL` | einem Label zugeordnet
| `milestone:MILESTONE` | einem Meilenstein zugeordnet
| `project:PROJECT` | einem Projekt zugeordnet
|===

.Filterkriterien für fehlende Angaben
[cols="1,3"]
|===
| Filter         | Beschreibung

| `no:label`     | keinem Label zugeordnet
| `no:milestone` | keinem Meilenstein zugeordnet
| `no:project`   | keinem Projekt zugeordnet
| `no:assignee`  | keinem Nutzer zugeordnet
|===

Ein Filter mit `is:issue is:open no:assignee` ist sehr hilfreich, um offenen
*Issues*, welchen keine Nutzer zur Bearbeitung zugeordnet sind, im Blick zu
haben. Über ein `sort:created-asc` lässt sich die Ausgabe zeitlich sortieren.

[NOTE]
======
Filter lassen sich aktuell nicht direkt in GitHub speichern, aber die
Seiten-URL enthält nach einer Suche den Filter und lässt sich so als Bookmark
speichern. Für das obere Beispiel würde die URL am Ende wie folgt aussehen: +
`/issues?q=is:open+is:issue+no:assignee+sort:created-asc`
======
=====
====

{section-separator}

==== GitHub Project Filter

Nützliche Filter für GitHub Project Sichten:

- `sprint:@current` - Alle Issues, welche dem aktuellen Sprint zugeordnet sind
- `no:sprint` - Alle Issues, welche keinem Sprint zugeordnet sind
- `assignee:@me` - Alle Issues, welche mir zugeordnet sind
- `is:closed` - Alle geschlossenen Issues


include::sitemap.inc.adoc[]
