
.⚠️ Vorbereitung vor Praktikumsbeginn
[%collapsible]
====
=====
Vor Beginn der Praktika ist sicherzustellen, dass die benötigten
Arbeitsumgebungen eingerichtet sind.

.Checkliste
- [x] https://github.com/[GitHub] Webseite geöffnet und eingeloggt
- [x] https://git-scm.com/[Git] ist konfiguriert (_.gitconfig_ vorhanden)
- [x] https://code.visualstudio.com/[Visual Studio Code] mit der
  AsciiDoc-Erweiterung ist vorhanden
- [x] (optional) Projekt-Repository in GitHub geöffnet
- [x] (optional) Projekt-Verzeichnis in VS Code als Ordner geöffnet

[WARNING]
======
In den *Windows*-Laboren werden die Nutzer-Profile nicht gespeichert.
Daher müssen die Arbeitsumgebungen vor jedem Praktikum neu eingerichtet werden.

Dies betrifft insbesondere die Git-Konfiguration, die Visual Studio
Code-Einstellungen und den Zugriff auf GitHub.

======

.Hinweise: Git konfigurieren (_.gitconfig_)
[%collapsible]
======
.Wiederherstellung einer existierenden _.gitconfig_
Kopieren Sie die vorhandenen _.gitconfig_ Datei nach `C:\Users\<username>\.gitconfig`.

TIP: Es empfiehlt sich die _.gitconfig_ im Netzlaufwerk `U:` zu speichern, da
dieses Laufwerk in allen Laboren der Fakultät verfügbar ist.

.Anlegen per Editor
[source,ini]
----
[user]
  name = Vorname Nachname
  email = vorname.nachname@stud.htw-dresden.de
  # email = s00000@htw-dresden.de
[safe]
  directory = *
----

.Anlegen per Git-Kommandos im Terminal
[source,console]
----
> git config --global user.name "Vorname Nachname"
> git config --global user.email vorname.nachname@stud.htw-dresden.de
> git config --global --add safe.directory *
----
======

.Hinweise: Visual Studio Code einrichten
[%collapsible]
======
. Installieren der benötigten Erweiterungen:
** https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode[AsciiDoc]
   vom _asciidoctor_ Projekt.
. Anpassen der AsciiDoc-Einstellungen:
** Asciidoc > Preview: *Use Editor Style*: icon:square-o[] (deaktiviert)
** Asciidoc > Extensions: *Enable Kroki*: icon:check-square-o[] (aktiviert)
======

.Hinweise: GitHub-Repository klonen
[%collapsible]
======
Eine lokale Arbeitskopie des Projekt-Repositorys kann mit dem Git-Kommando `git
clone` erstellt werden:

[source,console]
----
> cd path/to/projects/
> git clone https://github.com/.../<repo-name>
----

TIP: In den Laboren der Fakultät ist das Netzlaufwerk `U:` verfügbar. Dort
können die Arbeitskopien persistent abgelegt werden.
======
=====
====
